language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - 1.8.7
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - rbx-head
  - ree

before_script:
  - psql -c 'create database hyperion_ruby;' -U postgres

script: rake spec
